name: Experiment1

on:
  push:
    branches:
      - "main"
      - "staging"

jobs:
  build-web-atlas-job:
    runs-on: ubuntu-latest
    name: Building
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & Compilation
        run: |
          echo "Branch: ${DOTENVFILE}"
          cp -rf "./web-atlas-ts/.env.${DOTENVFILE}.sample" ./web-atlas-ts/.env
        env:
          DOTENVFILE: "${{ github.ref }} === 'refs/heads/main' && 'production' || 'staging'"

